version: '2.2'

services:
  elasticsearch:
    image: elasticsearch:6.4.1
    environment:
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: kibana:6.4.1
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601

volumes:
  esdata:
    driver: local
